/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cwtcheveacokpixghfvv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dGNoZXZlYWNva3BpeGdoZnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDg0MDgsImV4cCI6MjA3MDg4NDQwOH0.r_OlUyMWWAc-EkHOOKkEuOkuNDBD4eJ1hCVYf0-I-To"